# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 豆腐君的又一个博客
email: toufukun233(a)gmail.com
description: > # this means to ignore newlines until "baseurl:"
  豆腐君的又一个博客，可能会更新，更可能不会，所以请不要抱任何期待。
copyright: >
  Copyright (C) 2015-2016 Toufukun, all rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://toufukun.github.io" # the base hostname & protocol for your site
twitter_username: toufukun233
github_username: Toufukun
sina_weibo_username: toufukun

# Build settings
markdown: kramdown
